Several fixes to make Unit Tests pass: * HTTPUtils.cs: I ran into the case where e.Response was null and that threw a NullReferenceException. That is now prevented. * KeepAlive.test.cs: Added 'Ignore' Attribute to Test Method 'TestKeepAliveWithTimeout' as Timo mentioned earlier that those tests are not yet working as the KeepAlive Mechanism isn't yet stable in the web services branch. * Test.AP.cs: Use different approach to determine whether a ValidationResult is Empty - the old approach didn't work any longer as the TVerificationResultCollection no longer inherits from CollectionBase.
Other changes to Unit Tests:
* CorporateRate.test.cs, DailyRate.test.cs: include the full Exception text in the Assert.Fail Message to be better able to find out when a connection to the server failed (see next paragraph!).


!!! FAILING UNIT TESTS !!!
At present I get non-deterministic Unit Test failures with the message 'SetUp : Failed to connect to the Petra Server.  Have you forgotten to launch the Server Console? Exception: 
System.NotSupportedException: WebClient does not support concurrent I/O operations.' The place where those Exceptions occur, and the number of those Exceptions, changes with every NUnit Test run!